version: '3'
services:
  db:
    build: ./mysql
    image: mysql-ubuntu
    volumes:
      - /mnt/db_data:/var/lib/mysql
    # Discuss to see if maybe we should consider not exposing this port
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: justatestpass
      MYSQL_DATABASE: testdatabase
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword

  web:
    build: ./web
    depends_on:
      - db
    image: web-ubuntu
    volumes:
      - /mnt/web_data:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      DB_HOST: db:3306
      DB_USER: testuser
      DB_PASSWORD: testpassword
volumes:
    db_data:
    web_data:
